// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef Driver_h
#define Driver_h
#include <FL/Fl.H>
#include "ACanvas.h"

class Driver {
public:
  ACanvas* make_window();
  ACanvas *canvas;
};
#endif
